version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./gestaoMecanicaBack-main
    command: sh -c "pip install django-rest-passwordreset==1.5.0 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./gestaoMecanicaBack-main:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./gestaoMecanicaFront-main
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./gestaoMecanicaFront-main:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data:
