# Generated by Django 5.1.5 on 2026-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='nivel_acesso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
