# Generated by Django 5.1.5 on 2026-06-12 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_peca_origem_externa_notafiscalpendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoservico',
            name='foto',
            field=models.ImageField(upload_to='fotos_servicos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
